# /docker-compose.override.yml
services:
  app:
    build: .
    user: "${HOST_USER:-1001:1001}"
    volumes:
      - ./source:/var/www/html
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/zzz-uploads.ini:/usr/local/etc/php/conf.d/zzz-uploads.ini:ro
    networks:
      default:


  web:
    volumes:
      - ./source:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      default:
      proxy:

    labels:
      - "traefik.enable=true"
      # domain
      - "traefik.http.routers.wp.rule=Host(`${APP_DOMAIN}`)"
      # entrypoint https
      - "traefik.http.routers.wp.entrypoints=websecure"
      # bật TLS
      - "traefik.http.routers.wp.tls=true"
      # port nginx bên trong container
      - "traefik.http.services.wp.loadbalancer.server.port=80"

  db:
    networks:
      default:
      

networks:
  proxy:
    external: true