# /docker-compose.prod.yml
services:
  app:
    build: .
    user: "${HOST_USER:-www-data:www-data}"
    image: ${APP_IMAGE:-app-php}:${APP_VERSION:-latest}
    restart: always
    volumes:
      - wp_uploads:/var/www/html/wp-content/uploads
      # Configs are now COPY-ed in Dockerfile, so no binding needed unless you want to override
    networks:
      default:

  web:
    build:
      context: .
      dockerfile: Dockerfile-Web
    image: ${WEB_IMAGE:-app-nginx}:${APP_VERSION:-latest}
    restart: always
    volumes:
      - wp_uploads:/var/www/html/wp-content/uploads:ro
      # Config is now COPY-ed in Dockerfile, so no binding needed unless you want to override
    networks:
      default:
      proxy:

  db:
    networks:
      default:


networks:
  proxy:
    external: true
    

volumes:
  wp_uploads:
    name: ${VOLUME_UPLOADS}
    external: true