# /docker-compose.pma.yml
# pma production
# docker compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.pma.yml up -d pma
# docker compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.pma.yml stop pma

# pma local
# docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.pma.yml up -d pma
# docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.pma.yml stop pma

services:
  pma:
    image: phpmyadmin:latest
    profiles:
      - donotstart # Đảm bảo không tự động khởi động cùng docker compose up
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 500M
    ports:
      - "${PMA_PORT:-9999}:80"
    networks:
      - default